# Generated by Django 5.2.1 on 2025-05-26 21:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacilitesPoligons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True)),
                ("description", models.CharField(max_length=167, null=True)),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                "indexes": [models.Index(fields=["geom"], name="geom_index")],
            },
        ),
    ]
