# Generated by Django 5.2.1 on 2025-05-26 21:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitesPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True)),
                ("description", models.CharField(max_length=167, null=True)),
                (
                    "geom_point",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["geom_point"], name="geom_point_index")
                ],
            },
        ),
    ]
